version: '3'
services:
  service-locator:
    image: consul:0.8.3
    container_name: consul
    hostname: locator
    ports:
      - 8500:8500
  backend-echo:
    image: spike/echo
    hostname: backend-echo
    depends_on:
      - service-locator
    links:
      - service-locator:locator
    ports:
     - 9000
